Controllers/RandevuController.cs
using System.Drawing;
using System.Globalization;
using AspWebProgram.Models;
using AspWebProgramming.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace Controllers
{
    public class RandevuController : Controller
    {
        private DataContext dbcontext;

        public RandevuController(DataContext context)
        {
            dbcontext = context;

        }
        public async Task<IActionResult> IndexRandevu()
        {
            var userRole = HttpContext.Session.GetString("UserRole");
            var loginName = HttpContext.Session.GetString("LoginName");
           if (userRole != "Admin" && userRole != "Hasta" &&userRole!="Doktor")
            {
                return Unauthorized();
            }
            IQueryable<Randevu> query = dbcontext.Randevular
                .Include(x => x.Doktor)
                .Include(x => x.Hasta);

            if (userRole == "Hasta")
            {
                // Eğer kullanıcı "Hasta" ise, yalnızca o kullanıcının randevularını getir
                query = query.Where(x => x.Hasta.HastaTc == loginName);
            }
            else if (userRole == "Doktor")
            {
                query = query.Where(x => x.Doktor.DoktorTc == loginName);
            }

            var randevular = await query.ToListAsync();
            return View(randevular);
        }
        // public async Task<IActionResult> IndexRandevu()
        // {
        //     var userRole = HttpContext.Session.GetString("UserRole");
        //     var loginName = HttpContext.Session.GetString("LoginName");
        //     var randevular = await dbcontext.Randevular
        //     .Include(x => x.Doktor)
        //     .Include(x => x.Hasta)
        //     .ToListAsync();
        //     return View(randevular);
        // }
        [HttpGet]
        public async Task<IActionResult> RandevuOlustur()
        {
            var userRole = HttpContext.Session.GetString("UserRole");
            var loginName = HttpContext.Session.GetString("LoginName");
            ViewBag.Hastalar = new SelectList(await dbcontext.Hastalar.ToListAsync(), "HastaId", "HastaAd");
            if (userRole != "Admin" && userRole != "Hasta")
            {
                return Unauthorized();
            }
            if (userRole == "Hasta")
            {
                var hasta = await dbcontext.Hastalar.FirstOrDefaultAsync(h => h.HastaTc == loginName);
                if (hasta != null)
                {
                    ViewBag.Hastalar = new SelectList(new List<Hasta> { hasta }, "HastaId", "HastaAd");

                }
            }
            else if(userRole=="Admin")
            {
                ViewBag.Hastalar = new SelectList(await dbcontext.Hastalar.ToListAsync(), "HastaId", "HastaAd");
            }


            ViewBag.Doktorlar = new SelectList(await dbcontext.Doktorlar.ToListAsync(), "DoktorId", "DoktorAdSoyad");
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> GetRandevuSaatleriJsonForEdit(DateTime secilenTarih, int randevuId)
        {
            var saatler = await GetRandevuSaatleriEdit(secilenTarih, randevuId);
            return Json(new SelectList(saatler, "Value", "Text"));
        }
        [HttpGet]
        public async Task<IActionResult> GetRandevuSaatleriJson(DateTime secilenTarih, int doktorId)
        {
            var saatler = await GetRandevuSaatleri(secilenTarih, doktorId);
            return Json(new SelectList(saatler, "Value", "Text"));
        }
        private async Task<List<SelectListItem>> GetRandevuSaatleriEdit(DateTime randevuTarihi, int randevuId)
        {
            var mevcutRandevu = await dbcontext.Randevular.FindAsync(randevuId);
            var mevcutRandevuSaati = mevcutRandevu?.RandevuSaati;

            var alinanSaatler = await dbcontext.Randevular
                .Where(r => r.RandevuTarih.Date == randevuTarihi.Date && r.RandevuId != randevuId)
                .Select(r => r.RandevuSaati)
                .ToListAsync();

            var saatler = new List<SelectListItem>();
            var baslangic = new TimeSpan(9, 0, 0);
            var bitis = new TimeSpan(17, 0, 0);
            var aralik = TimeSpan.FromMinutes(30);

            for (var saat = baslangic; saat < bitis; saat += aralik)
            {
                if (!alinanSaatler.Contains(saat) || saat == mevcutRandevuSaati)
                {
                    saatler.Add(new SelectListItem
                    {
                        Value = saat.ToString(@"hh\:mm"),
                        Text = saat.ToString(@"hh\:mm"),
                        Selected = saat == mevcutRandevuSaati
                    });
                }
            }

            return saatler;
        }
        private async Task<List<SelectListItem>> GetRandevuSaatleri(DateTime randevuTarihi, int doktorId)
        {

            var alinanSaatler = await dbcontext.Randevular
                .Where(r => r.RandevuTarih.Date == randevuTarihi.Date && r.DoktorId == doktorId)
                .Select(r => r.RandevuSaati)
                .ToListAsync();

            var saatler = new List<SelectListItem>();
            var baslangic = new TimeSpan(9, 0, 0);
            var bitis = new TimeSpan(17, 0, 0);
            var aralik = TimeSpan.FromMinutes(30);

            for (var saat = baslangic; saat < bitis; saat += aralik)
            {
                if (!alinanSaatler.Contains(saat))
                {
                    saatler.Add(new SelectListItem
                    {
                        Value = saat.ToString(),
                        Text = saat.ToString(@"hh\:mm")
                    });
                }
            }

            return saatler;
        }

        // private async Task<List<SelectListItem>> GetRandevuSaatleri(DateTime? secilenTarih)
        // {
        //     var mevcutRandevular = new HashSet<TimeSpan>();

        //     if (secilenTarih.HasValue)
        //     {
        //         var randevuTarihleri = await dbcontext.Randevular
        //             .Where(r => r.RandevuTarih.Date == secilenTarih.Value.Date)
        //             .Select(r => r.RandevuTarih.TimeOfDay)
        //             .ToListAsync();

        //         mevcutRandevular = new HashSet<TimeSpan>(randevuTarihleri);
        //     }

        //     var saatler = new List<SelectListItem>();
        //     var baslangic = new TimeSpan(9, 0, 0); // Sabah 9:00
        //     var bitis = new TimeSpan(17, 0, 0);    // Akşam 5:00

        //     for (var saat = baslangic; saat < bitis; saat = saat.Add(TimeSpan.FromMinutes(30)))
        //     {
        //         if (!mevcutRandevular.Contains(saat))
        //         {
        //             saatler.Add(new SelectListItem { Value = saat.ToString(), Text = saat.ToString(@"hh\:mm") });
        //         }
        //     }

        //     return saatler;
        // }
        [HttpPost]
        public async Task<IActionResult> RandevuOlustur(Randevu model)
        {
            var userRole = HttpContext.Session.GetString("UserRole");
            if (userRole != "Admin" && userRole != "Hasta")
            {
                return Unauthorized();
            }
            dbcontext.Randevular.Add(model);
            await dbcontext.SaveChangesAsync();
            return RedirectToAction("Index", "Home");
        }
        // [HttpGet]
        // public IActionResult Edit(int id)
        // {
        //     var randevu = dbcontext.Randevular.SingleOrDefault(r => r.RandevuId == id);
        //     if (randevu == null)
        //     {
        //         return NotFound();
        //     }

        //     var viewModel = new RandevuEditViewModel
        //     {
        //         RandevuId = randevu.RandevuId,
        //         HastaId = randevu.HastaId,
        //         DoktorId = randevu.DoktorId,
        //         RandevuTarih = randevu.RandevuTarih,
        //         RandevuSaati = randevu.RandevuSaati
        //     };

        //     ViewBag.Hastalar = new SelectList(dbcontext.Hastalar, "HastaId", "HastaAd", randevu.HastaId);
        //     ViewBag.Doktorlar = new SelectList(dbcontext.Doktorlar, "DoktorId", "DoktorAd", randevu.DoktorId);
        //     return View(viewModel);
        // }
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var userRole = HttpContext.Session.GetString("UserRole");
            if (userRole != "Admin" && userRole != "Hasta")
            {
                return Unauthorized();
            }
            var loginName = HttpContext.Session.GetString("LoginName");


            var randevu = await dbcontext.Randevular
                .Include(r => r.Hasta)
                .Include(r => r.Doktor)
                .SingleOrDefaultAsync(r => r.RandevuId == id);
            if (userRole == "Hasta")
            {
                var hasta = await dbcontext.Hastalar.FirstOrDefaultAsync(h => h.HastaTc == loginName);
                if (hasta != null)
                {
                    ViewBag.Hastalar = new SelectList(new List<Hasta> { hasta }, "HastaId", "HastaAd", randevu.RandevuId);

                }
            }
            else{
                ViewBag.Hastalar = new SelectList(dbcontext.Hastalar, "HastaId", "HastaAd", randevu.HastaId);
            }
            if (randevu == null)
            {
                return NotFound();
            }

            var viewModel = new RandevuEditViewModel
            {
                RandevuId = randevu.RandevuId,
                HastaId = randevu.HastaId,
                DoktorId = randevu.DoktorId,
                RandevuTarih = randevu.RandevuTarih,
                RandevuSaati = randevu.RandevuSaati
            };

            //ViewBag.Hastalar = new SelectList(dbcontext.Hastalar, "HastaId", "HastaAd", randevu.HastaId);

Views/Shared/_Layout.cshtml
@inject IHttpContextAccessor HttpContextAccessor

@{
var username = HttpContextAccessor.HttpContext.Session.GetString("Username");
bool isLoggedIn = !string.IsNullOrEmpty(username);
var userRole = HttpContextAccessor.HttpContext.Session.GetString("UserRole");
ViewData["UserRole"] = userRole;
}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AspWebProgram</title>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AspWebProgram.styles.css" asp-append-version="true" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AspWebProgram</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (isLoggedIn)
                        {
                        if (userRole == "Hasta")
                        {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Randevu"
                                asp-action="RandevuOlustur">@_localization.GetKey("Randevu Oluştur")</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Doktor"
                                asp-action="Index">@_localization.GetKey("Doktorları Listele")</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Randevu"
                                asp-action="IndexRandevu">@_localization.GetKey("Randevu Listele")</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Hasta"
                                asp-action="Index">@_localization.GetKey("Hastaları Listele")</a>
                        </li>
                        }
                        else if(userRole=="Doktor")
                        {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Doktor"
                                asp-action="Index">@_localization.GetKey("Profil Ayarları")</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Randevu"
                                asp-action="IndexRandevu">@_localization.GetKey("Randevu Listele")</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Hasta"
                                asp-action="Index">@_localization.GetKey("Hastaları Listele")</a>
                        </li>
                        }
                        else if(userRole=="Admin")
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Hasta"
                                    asp-action="Index">@_localization.GetKey("Hastaları Listele")</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Randevu"
                                    asp-action="RandevuOlustur">@_localization.GetKey("Randevu Oluştur")</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Doktor"
                                    asp-action="Index">@_localization.GetKey("Doktorları Listele")</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Randevu"
                                    asp-action="IndexRandevu">@_localization.GetKey("Randevu Listele")</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Account"
                                    asp-action="Register">@_localization.GetKey("Hasta Ekle")</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Doktor" asp-action="Register">@_localization.GetKey("Doktor Ekle")</a>
                            </li> 
                        }
                        }
                        @if (!isLoggedIn)
                        {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home"
                                asp-action="Index">@_localization.GetKey("Ana Sayfa")</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Account"
                                asp-action="Register">@_localization.GetKey("Kayıt Ol")</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account"
                                asp-action="Login">@_localization.GetKey("Giriş Yap")</a>
                        </li>

                        }
                        @if (!string.IsNullOrEmpty(username))
                        {
                        <li class="nav-item">
                            <a class="nav-link text-dark" href="#">@_localization.GetKey("Hoşgeldiniz"): @username</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account"
                                asp-action="Logout">@_localization.GetKey("Oturumu Kapat")</a>
                        </li>
                        }
                        <li>
                            <div class="dropdown">
                                <button type="button" class="btn btn-primary dropdown-toggle"
                                    data-bs-toggle="dropdown">Language</button>
                                <ul class="dropdown-menu">
                                    <li>
                                        <a asp-controller="Home" asp-action="ChangeLanguage" asp-route-culture="en-US"
                                            class="dropdown-item"><i class="flag-icon flag-icon-gb"></i>English</a>

                                    </li>
                                    <li>
                                        <a asp-controller="Home" asp-action="ChangeLanguage" asp-route-culture="tr-TR"
                                            class="dropdown-item">
                                            <i class="flag-icon flag-icon-gb"></i>Türkçe
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - AspWebProgram - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav navbar-right">
            @if (!string.IsNullOrEmpty(username))
            {
            <li><a href="#">@_localization.GetKey("Hoşgeldiniz"): @username</a></li>
            }
        </ul>
    </div>
</body>

</html>
@RenderSection("Scripts", required: false)
<script>
    $(document).ready(function () {
        $('.dropdown-menu .dropdown-item').on('click', function () {
            var selectedLanguage = $(this).text();
            $('.dropdown-toggle').text(selectedLanguage);
            localStorage.setItem('selectedLanguage', selectedLanguage);
        });

        var savedLanguage = localStorage.getItem('selectedLanguage');
        if (savedLanguage) {
            $('.dropdown-toggle').text(savedLanguage);
        }
    });
</script>